months = set(["january","february","march","april","may","june"])
print("\n printing the original set....")
print(months)
print("Adding more elements to the set...")
months.add("july")
months.add("August")
print("\n printing the modified set")
print(months)
print()
for i in months:
    print(i)